# docker-compose.yml
services:
  postgres:
    image: postgres:17
    container_name: mymis-postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: localdevpassword
      POSTGRES_DB: MyMIS
    ports:
      - "5432:5432"
    volumes:
      - mymis-pgdata:/var/lib/postgresql/data

volumes:
  mymis-pgdata:
